export interface Flashcard {
  id: string
  front: string
  back: string
  category: string
  difficulty: "foundation" | "intermediate" | "advanced"
  tags: string[]
}

export const flashcardsDatabase: Record<string, Flashcard[]> = {
  "business-law-concepts": [
    {
      id: "bl-001",
      front: "What are the key duties of directors under the Companies Act 2006?",
      back: "1. Duty to act within powers (s.171)\n2. Duty to promote success of company (s.172)\n3. Duty to exercise independent judgment (s.173)\n4. Duty to exercise reasonable care, skill and diligence (s.174)\n5. Duty to avoid conflicts of interest (s.175)\n6. Duty not to accept benefits from third parties (s.176)\n7. Duty to declare interest in proposed transactions (s.177)",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["directors", "duties", "companies-act"],
    },
    {
      id: "bl-002",
      front: "What is the business judgment rule?",
      back: "The business judgment rule protects directors from liability for business decisions made in good faith, with reasonable care, and in the best interests of the company. Courts will not second-guess business decisions unless there is evidence of bad faith, conflict of interest, or gross negligence.",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["directors", "liability", "business-judgment"],
    },
    {
      id: "bl-003",
      front: "What are the requirements for a valid company formation?",
      back: "1. Memorandum of Association signed by subscribers\n2. Articles of Association (or adoption of model articles)\n3. Application for registration (Form IN01)\n4. Statement of capital and initial shareholdings\n5. Statement of proposed officers\n6. Statement of compliance\n7. Payment of registration fee",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["company-formation", "incorporation", "requirements"],
    },
    {
      id: "bl-004",
      front: "What is the difference between ordinary and special resolutions?",
      back: "Ordinary Resolution: Requires simple majority (>50%) of votes cast. Used for routine business decisions.\n\nSpecial Resolution: Requires 75% majority of votes cast. Required for fundamental changes like:\n- Altering articles of association\n- Changing company name\n- Reducing share capital\n- Winding up the company",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["resolutions", "voting", "shareholders"],
    },
    {
      id: "bl-005",
      front: "What is wrongful trading and what are the consequences?",
      back: "Wrongful trading occurs when a director continues to trade when they knew or ought to have known there was no reasonable prospect of avoiding insolvent liquidation.\n\nConsequences:\n- Personal liability for company debts\n- Disqualification as director\n- Contribution order to company assets\n- Criminal penalties in some cases",
      category: "business-law-concepts",
      difficulty: "advanced",
      tags: ["insolvency", "wrongful-trading", "director-liability"],
    },
    {
      id: "bl-006",
      front: "What are the different types of companies under the Companies Act 2006?",
      back: "1. Private company limited by shares (Ltd)\n2. Public company limited by shares (PLC)\n3. Private company limited by guarantee\n4. Private unlimited company\n5. Community Interest Company (CIC)\n6. Charitable Incorporated Organisation (CIO)",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["company-types", "limited", "unlimited"],
    },
    {
      id: "bl-007",
      front: "What is the doctrine of ultra vires?",
      back: "Ultra vires means 'beyond the powers'. Historically, companies could only act within their objects clause. Now largely abolished by Companies Act 2006 s.31 - company has unrestricted objects unless articles specifically restrict them. Third parties protected by s.40.",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["ultra-vires", "objects-clause", "capacity"],
    },
    {
      id: "bl-008",
      front: "What are the requirements for calling a general meeting?",
      back: "Notice Requirements:\n- AGM: 21 clear days notice\n- Other meetings: 14 clear days (private), 21 clear days (public)\n- Special resolution: 14 clear days minimum\n- Can be shortened by 95% agreement (private) or 95% agreement (public)\n\nContent: time, date, place, general nature of business",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["general-meetings", "notice", "agm"],
    },
    {
      id: "bl-009",
      front: "What is the rule in Foss v Harbottle?",
      back: "The rule states that:\n1. The proper claimant in an action for a wrong done to a company is the company itself\n2. Where the alleged wrong is a transaction which might be made binding on the company by a simple majority of members, no individual member can sue\n\nExceptions: fraud on minority, ultra vires acts, special majorities required",
      category: "business-law-concepts",
      difficulty: "advanced",
      tags: ["foss-harbottle", "derivative-claims", "majority-rule"],
    },
    {
      id: "bl-010",
      front: "What are the different types of share capital?",
      back: "1. Nominal/Authorized Capital - Maximum amount company can issue\n2. Issued Capital - Shares actually issued to shareholders\n3. Called-up Capital - Amount company has required payment for\n4. Paid-up Capital - Amount actually paid by shareholders\n5. Uncalled Capital - Issued but not yet called for payment",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["share-capital", "nominal", "issued", "paid-up"],
    },
    {
      id: "bl-011",
      front: "What is a derivative claim?",
      back: "A derivative claim allows a member to bring proceedings on behalf of the company for a wrong done to the company. Requirements under Companies Act 2006 ss.260-264:\n1. Permission of court required\n2. Prima facie case established\n3. Acting in good faith\n4. Claim would promote success of company",
      category: "business-law-concepts",
      difficulty: "advanced",
      tags: ["derivative-claims", "minority-protection", "court-permission"],
    },
    {
      id: "bl-012",
      front: "What are pre-emption rights?",
      back: "Pre-emption rights give existing shareholders the right of first refusal when new shares are issued. Under Companies Act 2006 s.561:\n- Applies to allotment of equity securities for cash\n- Must offer to existing shareholders in proportion to holdings\n- Can be excluded by articles or special resolution",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["pre-emption", "share-allotment", "existing-shareholders"],
    },
    {
      id: "bl-013",
      front: "What is the difference between a member and a shareholder?",
      back: "Member: Person whose name appears on register of members\nShareholder: Person who holds shares in the company\n\nUsually the same person, but can differ:\n- Nominee arrangements\n- Transmission on death\n- Share transfers not yet registered\n\nMembership gives rights (voting, dividends, information)",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["members", "shareholders", "register"],
    },
    {
      id: "bl-014",
      front: "What are the rules for financial assistance?",
      back: "Companies Act 2006 s.678-680 prohibits public companies from giving financial assistance for acquisition of their own shares.\n\nExceptions:\n- Private companies (prohibition lifted)\n- Assistance not principal purpose\n- Incidental to larger purpose\n- Dividends, distributions in winding up\n- Loans in ordinary course of business",
      category: "business-law-concepts",
      difficulty: "advanced",
      tags: ["financial-assistance", "share-acquisition", "public-companies"],
    },
    {
      id: "bl-015",
      front: "What is piercing the corporate veil?",
      back: "Exceptional remedy where courts ignore separate legal personality. Very rare - only when:\n1. Evasion principle - company used to evade existing obligations\n2. Concealment principle - company used to conceal true facts\n\nKey cases: Salomon v Salomon (established separate personality), Prest v Petrodel (modern test)",
      category: "business-law-concepts",
      difficulty: "advanced",
      tags: ["corporate-veil", "separate-personality", "evasion"],
    },
    {
      id: "bl-016",
      front: "What are the different types of meetings?",
      back: "1. Annual General Meeting (AGM) - Required for public companies\n2. General Meeting - Any meeting of members\n3. Class Meeting - Meeting of particular class of shareholders\n4. Board Meeting - Meeting of directors\n5. Committee Meeting - Meeting of board committee",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["meetings", "agm", "board-meetings"],
    },
    {
      id: "bl-017",
      front: "What is the statutory contract?",
      back: "Companies Act 2006 s.33 creates a statutory contract between:\n1. Company and each member\n2. Members inter se (between themselves)\n\nBased on articles of association. Enforceable like any contract but subject to special rules. Can be altered by special resolution (s.21).",
      category: "business-law-concepts",
      difficulty: "intermediate",
      tags: ["statutory-contract", "articles", "members"],
    },
    {
      id: "bl-018",
      front: "What are the different types of directors?",
      back: "1. Executive Directors - Full-time, involved in day-to-day management\n2. Non-Executive Directors - Part-time, oversight role\n3. Independent Directors - No material relationship with company\n4. Shadow Directors - Not appointed but directors act on their instructions\n5. De facto Directors - Act as directors without appointment",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["directors", "executive", "shadow", "de-facto"],
    },
    {
      id: "bl-019",
      front: "What is the Companies House filing requirements?",
      back: "Annual Requirements:\n- Annual Return (Confirmation Statement) - annually\n- Annual Accounts - within 9 months (private) or 6 months (public)\n- Corporation Tax Return - within 12 months\n\nOther filings: changes to directors, registered office, share capital, articles",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["companies-house", "annual-return", "accounts"],
    },
    {
      id: "bl-020",
      front: "What are the rules for company names?",
      back: "Requirements:\n- Must end with 'Limited' or 'Ltd' (private) or 'Public Limited Company' or 'PLC'\n- Cannot be same as existing company\n- Cannot suggest government connection\n- Cannot be offensive\n- Cannot include sensitive words without approval\n\nChange requires special resolution and Companies House approval",
      category: "business-law-concepts",
      difficulty: "foundation",
      tags: ["company-names", "limited", "plc"],
    },
  ],

  "contract-law-principles": [
    {
      id: "cl-001",
      front: "What are the essential elements of a valid contract?",
      back: "1. Offer - Clear, definite proposal\n2. Acceptance - Unqualified agreement to offer terms\n3. Consideration - Something of value exchanged\n4. Intention to create legal relations\n5. Capacity - Legal ability to enter contracts\n6. Certainty - Terms must be sufficiently certain\n7. Legality - Purpose must be lawful",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["formation", "elements", "validity"],
    },
    {
      id: "cl-002",
      front: "What is the difference between a condition and a warranty?",
      back: "Condition: A fundamental term going to the root of the contract. Breach gives right to terminate and claim damages.\n\nWarranty: A less important term. Breach only gives right to damages, not termination.\n\nInnominate Terms: Classified based on consequences of breach (Hong Kong Fir Shipping).",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["terms", "breach", "remedies"],
    },
    {
      id: "cl-003",
      front: "What are the rules for acceptance of an offer?",
      back: "1. Must be communicated to offeror (except unilateral contracts)\n2. Must be unqualified (mirror image rule)\n3. Must be made by authorized person\n4. Must be made while offer is still open\n5. Silence cannot constitute acceptance\n6. Acceptance by conduct is possible\n7. Postal rule applies to postal acceptances",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["acceptance", "offer", "formation"],
    },
    {
      id: "cl-004",
      front: "What is the doctrine of frustration?",
      back: "Frustration occurs when an unforeseen event makes performance impossible, illegal, or radically different from what was contemplated.\n\nEffects:\n- Contract automatically terminates\n- Parties discharged from future obligations\n- Law Reform (Frustrated Contracts) Act 1943 governs restitution\n- No damages for non-performance",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["frustration", "discharge", "impossibility"],
    },
    {
      id: "cl-005",
      front: "What are the types of misrepresentation?",
      back: "1. Fraudulent - False statement made knowingly, without belief in truth, or recklessly\n2. Negligent - False statement made carelessly without reasonable grounds\n3. Innocent - False statement made honestly and with reasonable grounds\n\nRemedies vary: rescission available for all types, damages for fraudulent and negligent only.",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["misrepresentation", "fraud", "remedies"],
    },
    {
      id: "cl-006",
      front: "What is the postal rule?",
      back: "Acceptance by post is effective when posted, not when received (Adams v Lindsell). Applies when:\n1. Post is contemplated method of acceptance\n2. Letter properly addressed and stamped\n3. Posted in ordinary course\n\nDoes not apply to instantaneous communications (email, fax, telephone)",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["postal-rule", "acceptance", "communication"],
    },
    {
      id: "cl-007",
      front: "What is consideration and what are its rules?",
      back: "Consideration is something of value exchanged for a promise.\n\nRules:\n1. Must be sufficient but need not be adequate\n2. Must move from the promisee\n3. Must not be past (unless exceptions apply)\n4. Cannot be performance of existing duty\n5. Part payment of debt is not good consideration (Pinnel's case)",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["consideration", "sufficient", "adequate"],
    },
    {
      id: "cl-008",
      front: "What are the exceptions to the rule against past consideration?",
      back: "1. Lampleigh v Brathwait - Past act done at promisor's request with expectation of payment\n2. Bills of Exchange Act - Past consideration sufficient for bills\n3. Statute-barred debts - Promise to pay revives obligation\n4. Companies Act - Past consideration sufficient for allotment of shares",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["past-consideration", "lampleigh", "exceptions"],
    },
    {
      id: "cl-009",
      front: "What is the difference between an offer and an invitation to treat?",
      back: "Offer: Definite proposal capable of acceptance\nInvitation to Treat: Invitation to make an offer\n\nExamples of invitations to treat:\n- Shop window displays (Fisher v Bell)\n- Advertisements (Partridge v Crittenden)\n- Auction sales (except without reserve)\n- Tenders (except referential bids)",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["offer", "invitation-to-treat", "advertisements"],
    },
    {
      id: "cl-010",
      front: "What are the rules for termination of offers?",
      back: "Offers terminate by:\n1. Acceptance\n2. Rejection (including counter-offer)\n3. Revocation (must be communicated)\n4. Lapse of time\n5. Death of offeror/offeree\n6. Failure of condition\n7. Supervening illegality",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["termination", "revocation", "lapse"],
    },
    {
      id: "cl-011",
      front: "What is the battle of the forms?",
      back: "Occurs when parties exchange standard forms with conflicting terms. Courts apply 'last shot' doctrine - terms of last form sent before acceptance govern.\n\nAlternative: Butler Machine Tool - look for acceptance of original offer on its terms, not counter-offer.",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["battle-of-forms", "standard-terms", "last-shot"],
    },
    {
      id: "cl-012",
      front: "What is the parol evidence rule?",
      back: "Where parties have reduced their agreement to writing, extrinsic evidence cannot be used to add to, vary, or contradict the written terms.\n\nExceptions:\n- Rectification\n- Collateral contracts\n- Custom/trade usage\n- Subsequent variation\n- Invalidity of contract",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["parol-evidence", "written-contracts", "extrinsic-evidence"],
    },
    {
      id: "cl-013",
      front: "What are the different types of terms?",
      back: "Express Terms: Explicitly agreed by parties\nImplied Terms: Not expressly stated but part of contract\n- Implied by fact (necessary for business efficacy)\n- Implied by law (statutory or common law)\n- Implied by custom (trade usage)\n\nConditions, warranties, and innominate terms classify importance",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["express-terms", "implied-terms", "business-efficacy"],
    },
    {
      id: "cl-014",
      front: "What is the contra proferentem rule?",
      back: "Ambiguous terms are construed against the party who drafted them, especially exclusion clauses. Applies when:\n1. Genuine ambiguity exists\n2. Cannot be resolved by other interpretation methods\n3. Particularly strict for exclusion clauses\n\nAims to protect weaker party from unfair terms",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["contra-proferentem", "ambiguity", "exclusion-clauses"],
    },
    {
      id: "cl-015",
      front: "What are the requirements for incorporation of terms?",
      back: "Terms incorporated by:\n1. Signature - binds even if not read (L'Estrange v Graucob)\n2. Notice - reasonable notice before/at time of contract\n3. Course of dealing - consistent previous dealings\n4. Trade custom - well-known industry practice\n\nTiming crucial - must be before contract formation",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["incorporation", "signature", "notice"],
    },
    {
      id: "cl-016",
      front: "What is economic duress?",
      back: "Illegitimate pressure that leaves no practical alternative but to agree. Requirements:\n1. Illegitimate pressure applied\n2. Pressure significant cause of entering contract\n3. No practical alternative\n4. Protest made (or good reason for not protesting)\n\nRemedies: rescission, damages",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["economic-duress", "illegitimate-pressure", "rescission"],
    },
    {
      id: "cl-017",
      front: "What is undue influence?",
      back: "Actual Undue Influence: Claimant proves influence actually exercised\n\nPresumed Undue Influence:\n1. Relationship of trust and confidence\n2. Transaction calls for explanation\n3. No independent advice received\n\nSpecial relationships: solicitor-client, doctor-patient, parent-child (adult)",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["undue-influence", "trust-confidence", "independent-advice"],
    },
    {
      id: "cl-018",
      front: "What are the rules for penalty clauses?",
      back: "Penalty clauses are unenforceable. Distinction:\n\nLiquidated Damages: Genuine pre-estimate of loss - enforceable\nPenalty: Designed to deter breach - unenforceable\n\nTest: Would clause be unconscionable or extravagant? (Cavendish Square)",
      category: "contract-law-principles",
      difficulty: "advanced",
      tags: ["penalty-clauses", "liquidated-damages", "cavendish"],
    },
    {
      id: "cl-019",
      front: "What is the doctrine of privity?",
      back: "Only parties to a contract can sue or be sued on it. Third parties cannot enforce contracts even if made for their benefit.\n\nExceptions:\n- Contracts (Rights of Third Parties) Act 1999\n- Agency\n- Assignment\n- Trust of contractual rights\n- Statutory exceptions",
      category: "contract-law-principles",
      difficulty: "intermediate",
      tags: ["privity", "third-parties", "1999-act"],
    },
    {
      id: "cl-020",
      front: "What are the different types of breach?",
      back: "1. Actual Breach - Failure to perform when performance due\n2. Anticipatory Breach - Renunciation before performance due\n\nConsequences depend on term breached:\n- Condition: Right to terminate and damages\n- Warranty: Damages only\n- Innominate: Depends on consequences",
      category: "contract-law-principles",
      difficulty: "foundation",
      tags: ["breach", "actual", "anticipatory", "repudiation"],
    },
  ],

  "tort-law-fundamentals": [
    {
      id: "tl-001",
      front: "What are the elements of negligence?",
      back: "1. Duty of Care - Legal obligation owed to claimant\n2. Breach of Duty - Falling below reasonable standard\n3. Causation - Factual and legal causation established\n4. Remoteness - Damage not too remote\n5. Damage - Actual loss or harm suffered\n\nAll elements must be proven on balance of probabilities.",
      category: "tort-law-fundamentals",
      difficulty: "foundation",
      tags: ["negligence", "elements", "duty-of-care"],
    },
    {
      id: "tl-002",
      front: "What is the Caparo test for duty of care?",
      back: "Three-stage test from Caparo v Dickman:\n1. Foreseeability - Was harm reasonably foreseeable?\n2. Proximity - Is there sufficient legal proximity?\n3. Fair, just and reasonable - Would it be fair to impose duty?\n\nAll three elements must be satisfied to establish duty of care.",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["caparo", "duty-of-care", "foreseeability"],
    },
    {
      id: "tl-003",
      front: "What is the 'but for' test in causation?",
      back: "The 'but for' test asks: 'But for the defendant's breach, would the damage have occurred?'\n\nIf answer is NO - causation established\nIf answer is YES - no causation\n\nThis is the test for factual causation. Legal causation (remoteness) is separate and uses reasonable foreseeability test.",
      category: "tort-law-fundamentals",
      difficulty: "foundation",
      tags: ["causation", "but-for-test", "factual-causation"],
    },
    {
      id: "tl-004",
      front: "What are the rules for occupiers' liability?",
      back: "Occupiers' Liability Act 1957 (lawful visitors):\n- Duty to take reasonable care\n- Higher standard for children\n- Lower standard for skilled visitors\n\nOccupiers' Liability Act 1984 (trespassers):\n- Duty only if occupier aware of danger and visitor's presence\n- Lower standard of care\n- Warning may discharge duty",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["occupiers-liability", "visitors", "trespassers"],
    },
    {
      id: "tl-005",
      front: "What is vicarious liability?",
      back: "Vicarious liability makes one person liable for torts committed by another.\n\nRequirements:\n1. Relationship of employment/agency\n2. Tort committed in course of employment\n3. Close connection between employment and tort\n\nEmployer remains liable even if employee acted against instructions (Limpus v London General Omnibus).",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["vicarious-liability", "employment", "course-of-employment"],
    },
    {
      id: "tl-006",
      front: "What is the reasonable person test?",
      back: "Objective test for breach of duty - would a reasonable person in defendant's position have acted differently?\n\nFactors considered:\n- Magnitude of risk\n- Likelihood of harm\n- Seriousness of potential harm\n- Cost/practicality of precautions\n- Social utility of activity\n\nBased on Blyth v Birmingham Waterworks",
      category: "tort-law-fundamentals",
      difficulty: "foundation",
      tags: ["reasonable-person", "breach", "objective-test"],
    },
    {
      id: "tl-007",
      front: "What is the eggshell skull rule?",
      back: "You must take your victim as you find them. If claimant has unusual vulnerability (physical or psychiatric), defendant liable for full extent of harm even if unforeseeable.\n\nApplies to:\n- Physical conditions (thin skull)\n- Psychiatric conditions\n- Religious beliefs (refusing treatment)\n- Financial circumstances",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["eggshell-skull", "thin-skull", "vulnerability"],
    },
    {
      id: "tl-008",
      front: "What are the elements of the tort of nuisance?",
      back: "Private Nuisance:\n1. Indirect interference with land\n2. Unreasonable use of land\n3. Damage to claimant\n\nFactors for reasonableness:\n- Duration and frequency\n- Locality\n- Sensitivity of claimant's use\n- Malice\n- Social utility",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["nuisance", "unreasonable-use", "interference"],
    },
    {
      id: "tl-009",
      front: "What is the rule in Rylands v Fletcher?",
      back: "Strict liability for escape of dangerous things from land. Requirements:\n1. Bringing something onto land\n2. Non-natural use of land\n3. Thing likely to cause mischief if escapes\n4. Escape occurs\n5. Damage results\n\nDefences: act of stranger, act of God, statutory authority, consent",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["rylands-fletcher", "strict-liability", "escape"],
    },
    {
      id: "tl-010",
      front: "What are the defences to negligence?",
      back: "1. Contributory Negligence - Claimant's fault contributes to damage (damages reduced)\n2. Volenti non fit injuria - Voluntary assumption of risk (complete defence)\n3. Ex turpi causa - Illegality (complete defence)\n4. Limitation - Time limits for bringing claims",
      category: "tort-law-fundamentals",
      difficulty: "foundation",
      tags: ["defences", "contributory-negligence", "volenti"],
    },
    {
      id: "tl-011",
      front: "What is psychiatric harm and when is it recoverable?",
      back: "Primary Victims: Physically injured or in danger - can recover for psychiatric harm\n\nSecondary Victims: Witness harm to others - must satisfy Alcock criteria:\n1. Close ties of love and affection\n2. Proximity in time and space\n3. Perception by own senses\n4. Sudden shock (not gradual realization)",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["psychiatric-harm", "primary-victims", "alcock"],
    },
    {
      id: "tl-012",
      front: "What is pure economic loss and when is it recoverable?",
      back: "Pure economic loss (financial loss without physical damage) generally not recoverable in negligence.\n\nExceptions:\n1. Negligent misstatement (Hedley Byrne)\n2. Wills cases (White v Jones)\n3. Defective buildings (limited circumstances)\n4. Statutory duties",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["economic-loss", "hedley-byrne", "misstatement"],
    },
    {
      id: "tl-013",
      front: "What are the requirements for negligent misstatement?",
      back: "Hedley Byrne v Heller requirements:\n1. Special relationship of trust and confidence\n2. Voluntary assumption of responsibility\n3. Reasonable reliance by claimant\n4. Statement made in professional/business context\n5. Claimant acts on statement to their detriment",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["negligent-misstatement", "hedley-byrne", "reliance"],
    },
    {
      id: "tl-014",
      front: "What is the difference between trespass and negligence?",
      back: "Trespass:\n- Intentional or direct interference\n- Actionable per se (no damage required)\n- Burden on defendant to prove lawful justification\n\nNegligence:\n- Careless conduct\n- Damage must be proved\n- Burden on claimant to prove all elements",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["trespass", "negligence", "actionable-per-se"],
    },
    {
      id: "tl-015",
      front: "What are the elements of defamation?",
      back: "1. Statement is defamatory (lowers reputation)\n2. Statement refers to claimant\n3. Statement is published to third party\n\nDefences:\n- Truth (Defamation Act 2013)\n- Honest opinion\n- Publication on matter of public interest\n- Privilege (absolute or qualified)",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["defamation", "publication", "reputation"],
    },
    {
      id: "tl-016",
      front: "What is the test for remoteness of damage?",
      back: "Reasonable foreseeability test (The Wagon Mound):\n- Type of damage must be reasonably foreseeable\n- Exact way damage occurs need not be foreseeable\n- Extent of damage need not be foreseeable\n\nReplaced directness test (Re Polemis)",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["remoteness", "wagon-mound", "foreseeability"],
    },
    {
      id: "tl-017",
      front: "What is the tort of conversion?",
      back: "Wrongful dealing with goods inconsistent with owner's rights. Examples:\n- Taking goods\n- Disposing of goods\n- Refusing to return goods\n- Substantially altering goods\n\nStrict liability tort - intention irrelevant. Remedies: damages, return of goods",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["conversion", "goods", "strict-liability"],
    },
    {
      id: "tl-018",
      front: "What are the different types of damages in tort?",
      back: "1. Compensatory - Restore claimant to pre-tort position\n2. Aggravated - Additional compensation for injury to feelings\n3. Exemplary/Punitive - Punishment for outrageous conduct\n4. Nominal - Small sum when rights infringed but no loss\n5. Contemptuous - Derisory amount showing disapproval",
      category: "tort-law-fundamentals",
      difficulty: "foundation",
      tags: ["damages", "compensatory", "exemplary"],
    },
    {
      id: "tl-019",
      front: "What is the tort of passing off?",
      back: "Protects goodwill in business. Requirements (Jif Lemon test):\n1. Goodwill - Reputation in business\n2. Misrepresentation - Likely to deceive customers\n3. Damage - To goodwill or likely damage\n\nRemedies: injunction, damages, account of profits",
      category: "tort-law-fundamentals",
      difficulty: "intermediate",
      tags: ["passing-off", "goodwill", "misrepresentation"],
    },
    {
      id: "tl-020",
      front: "What is the tort of breach of confidence?",
      back: "Requirements (Coco v Clark):\n1. Information has necessary quality of confidence\n2. Information imparted in circumstances importing obligation of confidence\n3. Unauthorized use of information to detriment of confider\n\nDefences: public interest, prior publication",
      category: "tort-law-fundamentals",
      difficulty: "advanced",
      tags: ["breach-confidence", "coco-clark", "public-interest"],
    },
  ],

  "property-law-essentials": [
    {
      id: "pl-001",
      front: "What are the characteristics of freehold ownership?",
      back: "Freehold (fee simple absolute in possession):\n- Perpetual duration\n- Absolute ownership\n- In possession (immediate right to occupy)\n- Inheritable\n- Can be sold, mortgaged, or leased\n- Subject to planning laws and other statutory restrictions",
      category: "property-law-essentials",
      difficulty: "foundation",
      tags: ["freehold", "ownership", "fee-simple"],
    },
    {
      id: "pl-002",
      front: "What are the essential characteristics of a lease?",
      back: "Street v Mountford requirements:\n1. Exclusive possession - Right to exclude others including landlord\n2. Fixed or periodic term - Definite duration\n3. Rent - Consideration (though nominal rent acceptable)\n\nWithout exclusive possession, only a licence exists, not a lease.",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["lease", "licence", "exclusive-possession"],
    },
    {
      id: "pl-003",
      front: "What are the requirements for a valid easement?",
      back: "Re Ellenborough Park requirements:\n1. Dominant and servient tenement\n2. Easement must accommodate dominant tenement\n3. Dominant and servient owners must be different persons\n4. Right must be capable of forming subject matter of grant\n\nMust also be acquired by grant, reservation, prescription, or statute.",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["easements", "dominant-tenement", "servient-tenement"],
    },
    {
      id: "pl-004",
      front: "What is the difference between legal and equitable interests?",
      back: "Legal interests:\n- Recognized at common law\n- Bind the whole world\n- Must comply with formality requirements\n- Examples: freehold, lease over 7 years, legal mortgage\n\nEquitable interests:\n- Recognized in equity\n- May be defeated by bona fide purchaser for value without notice\n- Examples: beneficial interest under trust, equitable mortgage, restrictive covenant",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["legal-interests", "equitable-interests", "formalities"],
    },
    {
      id: "pl-005",
      front: "What are the rules for adverse possession?",
      back: "Requirements:\n1. Factual possession - Physical control of land\n2. Intention to possess - Animus possidendi\n3. Adverse possession - Without owner's permission\n4. Continuous possession for limitation period\n\nRegistered land: 10 years + application procedure\nUnregistered land: 12 years (Limitation Act 1980)",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["adverse-possession", "limitation", "factual-possession"],
    },
    {
      id: "pl-006",
      front: "What are the different types of co-ownership?",
      back: "Joint Tenancy:\n- Right of survivorship\n- Four unities (time, title, interest, possession)\n- Cannot leave share by will\n\nTenancy in Common:\n- No survivorship\n- Only unity of possession required\n- Can leave share by will\n- Unequal shares possible",
      category: "property-law-essentials",
      difficulty: "foundation",
      tags: ["co-ownership", "joint-tenancy", "tenancy-in-common"],
    },
    {
      id: "pl-007",
      front: "What are the four unities for joint tenancy?",
      back: "1. Unity of Time - Interests must vest at same time\n2. Unity of Title - Must derive from same document\n3. Unity of Interest - Same type and duration of interest\n4. Unity of Possession - Right to possess whole property\n\nIf any unity broken, becomes tenancy in common",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["four-unities", "joint-tenancy", "severance"],
    },
    {
      id: "pl-008",
      front: "What are the methods of severance of joint tenancy?",
      back: "1. Notice in writing (s.36(2) LPA 1925)\n2. Mutual agreement\n3. Mutual conduct (course of dealing)\n4. Unilateral act operating on own share\n5. Bankruptcy\n6. Charging order\n7. Homicide (forfeiture rule)",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["severance", "joint-tenancy", "notice"],
    },
    {
      id: "pl-009",
      front: "What is the difference between a mortgage and a charge?",
      back: "Legal Mortgage:\n- Transfer of legal estate subject to equity of redemption\n- Mortgagee has legal title\n- Right to possession\n\nCharge:\n- Security interest only\n- No transfer of title\n- Right to sell but not possess\n- Most modern mortgages are charges",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["mortgage", "charge", "equity-of-redemption"],
    },
    {
      id: "pl-010",
      front: "What are the formality requirements for land transactions?",
      back: "s.2 Law of Property (Miscellaneous Provisions) Act 1989:\n- Contract must be in writing\n- Incorporate all terms\n- Signed by both parties\n\ns.52 LPA 1925:\n- Conveyance must be by deed\n- Exceptions: leases ≤3 years, assignments of leases ≤3 years",
      category: "property-law-essentials",
      difficulty: "foundation",
      tags: ["formalities", "section-2", "deed"],
    },
    {
      id: "pl-011",
      front: "What are the requirements for a valid deed?",
      back: "s.1 Law of Property (Miscellaneous Provisions) Act 1989:\n1. Must be clear on face it's intended as deed\n2. Must be signed\n3. Signature must be witnessed\n4. Must be delivered\n\nNo consideration required for deed",
      category: "property-law-essentials",
      difficulty: "foundation",
      tags: ["deed", "signature", "witness", "delivery"],
    },
    {
      id: "pl-012",
      front: "What is the doctrine of notice?",
      back: "Equitable interests bind everyone except bona fide purchaser for value of legal estate without notice.\n\nTypes of notice:\n1. Actual - Real knowledge\n2. Constructive - Should have discovered on reasonable inquiry\n3. Imputed - Agent's knowledge imputed to principal\n\nOnly applies to unregistered land",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["notice", "bona-fide-purchaser", "equitable-interests"],
    },
    {
      id: "pl-013",
      front: "What are overriding interests?",
      back: "Interests that bind registered proprietor despite not being on register (Schedule 3 LRA 2002):\n1. Short leases (≤7 years)\n2. Interests of persons in actual occupation\n3. Legal easements and profits\n4. Customary rights\n5. Public rights\n6. Local land charges",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["overriding-interests", "actual-occupation", "schedule-3"],
    },
    {
      id: "pl-014",
      front: "What is actual occupation?",
      back: "Physical presence on land giving rise to overriding interest. Requirements:\n1. Actual occupation at time of disposition\n2. Interest subsisting at time of disposition\n3. Occupation obvious on reasonable inspection OR purchaser has actual knowledge\n\nKey cases: Williams & Glyn's Bank v Boland, Lloyds Bank v Rosset",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["actual-occupation", "boland", "physical-presence"],
    },
    {
      id: "pl-015",
      front: "What are the different types of leases?",
      back: "1. Fixed Term - Definite start and end date\n2. Periodic - Continues from period to period\n3. Lease for life - Until death of specified person\n4. Tenancy at will - Terminable at any time\n5. Tenancy at sufferance - Holding over after lease expires\n6. Tenancy by estoppel - Created by conduct",
      category: "property-law-essentials",
      difficulty: "foundation",
      tags: ["lease-types", "fixed-term", "periodic"],
    },
    {
      id: "pl-016",
      front: "What are the landlord's remedies for breach of covenant?",
      back: "1. Action for debt (rent arrears)\n2. Distress/Commercial rent arrears recovery\n3. Forfeiture (for breach of any covenant)\n4. Damages\n5. Specific performance (rare)\n6. Injunction\n7. Self-help (limited circumstances)",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["landlord-remedies", "forfeiture", "distress"],
    },
    {
      id: "pl-017",
      front: "What are the rules for forfeiture?",
      back: "Requirements:\n1. Right of re-entry reserved in lease\n2. Breach of covenant\n3. Proper notice (s.146 LPA 1925 for non-rent)\n4. Reasonable time to remedy (if capable)\n\nMethods: peaceable re-entry or court proceedings\nRelief available to tenant and subtenants",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["forfeiture", "section-146", "relief"],
    },
    {
      id: "pl-018",
      front: "What is the difference between assignment and subletting?",
      back: "Assignment:\n- Transfer of whole remaining term\n- Assignee becomes tenant\n- Privity of estate created\n- Original tenant may remain liable\n\nSubletting:\n- Grant of shorter term\n- Sublessor remains tenant\n- No privity between head landlord and subtenant",
      category: "property-law-essentials",
      difficulty: "intermediate",
      tags: ["assignment", "subletting", "privity-of-estate"],
    },
    {
      id: "pl-019",
      front: "What are restrictive covenants?",
      back: "Negative obligations binding successors in title. Requirements (Tulk v Moxhay):\n1. Covenant must be negative\n2. Covenant must accommodate dominant land\n3. Covenant must be made for benefit of land retained\n4. Successor must have notice\n\nPositive covenants do not run with freehold land",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["restrictive-covenants", "tulk-moxhay", "negative"],
    },
    {
      id: "pl-020",
      front: "What is proprietary estoppel?",
      back: "Equity prevents landowner from asserting strict legal rights. Requirements:\n1. Assurance - Representation about rights\n2. Reliance - Acting on assurance\n3. Detriment - Suffering loss as result\n\nRemedies: transfer of land, monetary compensation, licence to occupy",
      category: "property-law-essentials",
      difficulty: "advanced",
      tags: ["proprietary-estoppel", "assurance", "reliance", "detriment"],
    },
  ],

  "criminal-law-principles": [
    {
      id: "crl-001",
      front: "What is the difference between actus reus and mens rea?",
      back: "Actus Reus - The guilty act:\n- Physical element of crime\n- Can be act, omission, or state of affairs\n- Must be voluntary\n- Includes circumstances and consequences\n\nMens Rea - The guilty mind:\n- Mental element of crime\n- Intention, recklessness, or negligence\n- Must coincide with actus reus\n- Specific to each offence",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["actus-reus", "mens-rea", "elements"],
    },
    {
      id: "crl-002",
      front: "What are the different types of intention?",
      back: "Direct Intention:\n- Defendant's aim or purpose\n- Consequence is desired outcome\n\nOblique/Indirect Intention:\n- Consequence not desired but virtually certain\n- Defendant appreciates virtual certainty\n- Jury may find intention (Woollin direction)",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["intention", "direct-intention", "oblique-intention"],
    },
    {
      id: "crl-003",
      front: "What is the definition of murder?",
      back: "Murder is the unlawful killing of a human being under the Queen's Peace with malice aforethought.\n\nElements:\n- Unlawful killing (actus reus)\n- Of human being\n- Under Queen's Peace\n- With malice aforethought (intention to kill or cause GBH)\n\nMandatory life sentence.",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["murder", "unlawful-killing", "malice-aforethought"],
    },
    {
      id: "crl-004",
      front: "What are the elements of theft under s.1 Theft Act 1968?",
      back: "A person is guilty of theft if he dishonestly appropriates property belonging to another with intention to permanently deprive.\n\nElements:\n1. Appropriation (s.3)\n2. Property (s.4)\n3. Belonging to another (s.5)\n4. Dishonesty (s.2 + Ghosh test)\n5. Intention to permanently deprive (s.6)",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["theft", "appropriation", "dishonesty"],
    },
    {
      id: "crl-005",
      front: "What is the defence of self-defence?",
      back: "Requirements:\n1. Necessity - Force necessary to defend self/others/property\n2. Reasonableness - Force used must be reasonable in circumstances\n3. Imminence - Threat must be imminent or immediately forthcoming\n\nSubjective test for necessity, objective test for reasonableness.\nNo duty to retreat but relevant to reasonableness.",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["self-defence", "necessity", "reasonableness"],
    },
    {
      id: "crl-006",
      front: "What is recklessness in criminal law?",
      back: "Cunningham Recklessness (subjective):\n- Defendant foresees risk of consequence\n- Unreasonable to take that risk\n- Goes ahead anyway\n\nApplies to most offences requiring recklessness.\nCaldwell recklessness (objective) now largely abolished.",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["recklessness", "cunningham", "subjective"],
    },
    {
      id: "crl-007",
      front: "What are the different types of manslaughter?",
      back: "Voluntary Manslaughter:\n- Murder reduced by partial defence\n- Diminished responsibility, loss of control, suicide pact\n\nInvoluntary Manslaughter:\n- Unlawful act manslaughter\n- Gross negligence manslaughter\n- Corporate manslaughter",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["manslaughter", "voluntary", "involuntary"],
    },
    {
      id: "crl-008",
      front: "What is unlawful act manslaughter?",
      back: "Requirements (DPP v Newbury):\n1. Intentional act\n2. Act is unlawful (criminal offence)\n3. Act is dangerous (risk of some harm to someone)\n4. Act causes death\n\nObjective test for dangerousness - would sober and reasonable person recognise risk?",
      category: "criminal-law-principles",
      difficulty: "advanced",
      tags: ["unlawful-act-manslaughter", "dangerous", "newbury"],
    },
    {
      id: "crl-009",
      front: "What is gross negligence manslaughter?",
      back: "Requirements (Adomako):\n1. Duty of care owed to victim\n2. Breach of that duty\n3. Breach causes death\n4. Breach so gross as to justify criminal conviction\n\nCircular test - jury decides if negligence gross enough for criminal liability",
      category: "criminal-law-principles",
      difficulty: "advanced",
      tags: ["gross-negligence-manslaughter", "adomako", "duty-of-care"],
    },
    {
      id: "crl-010",
      front: "What is the defence of diminished responsibility?",
      back: "s.2 Homicide Act 1957 (amended 2009):\n1. Abnormality of mental functioning\n2. Arising from recognised medical condition\n3. Substantially impairs ability to understand conduct, form rational judgment, or exercise self-control\n4. Provides explanation for killing\n\nPartial defence to murder only",
      category: "criminal-law-principles",
      difficulty: "advanced",
      tags: ["diminished-responsibility", "abnormality", "medical-condition"],
    },
    {
      id: "crl-011",
      front: "What is the defence of loss of control?",
      back: "s.54 Coroners and Justice Act 2009:\n1. Loss of self-control\n2. Qualifying trigger (fear/anger)\n3. Person of same age/sex with normal tolerance might have reacted similarly\n\nNo requirement for sudden loss of control.\nPartial defence to murder only.",
      category: "criminal-law-principles",
      difficulty: "advanced",
      tags: ["loss-of-control", "qualifying-trigger", "normal-tolerance"],
    },
    {
      id: "crl-012",
      front: "What are the elements of assault and battery?",
      back: "Assault:\n- Intentionally or recklessly\n- Causing victim to apprehend\n- Immediate unlawful personal violence\n\nBattery:\n- Intentionally or recklessly\n- Applying unlawful force\n- To another person\n\nNo need for injury in either offence",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["assault", "battery", "apprehend", "force"],
    },
    {
      id: "crl-013",
      front: "What is s.47 ABH?",
      back: "Assault occasioning actual bodily harm (s.47 OAPA 1861):\n- Assault or battery\n- Causing actual bodily harm\n- Mens rea for assault/battery only\n\nABH: more than trivial harm (bruising, cuts, psychiatric harm)\nNo need to intend or foresee ABH",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["abh", "actual-bodily-harm", "section-47"],
    },
    {
      id: "crl-014",
      front: "What is s.20 GBH?",
      back: "Unlawfully and maliciously wounding or inflicting GBH (s.20 OAPA 1861):\n- Wound (break in continuity of skin) OR\n- Grievous bodily harm (serious harm)\n- Intention or recklessness as to some harm\n\nLower mens rea than s.18 - only need foresee some harm",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["gbh", "section-20", "wound", "maliciously"],
    },
    {
      id: "crl-015",
      front: "What is s.18 GBH?",
      back: "Unlawfully and maliciously wounding or causing GBH with intent (s.18 OAPA 1861):\n- Wound OR grievous bodily harm\n- With intent to cause GBH OR\n- With intent to resist/prevent arrest\n\nHigher mens rea than s.20 - must intend GBH or resist arrest",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["gbh", "section-18", "intent", "resist-arrest"],
    },
    {
      id: "crl-016",
      front: "What is appropriation in theft?",
      back: "s.3 Theft Act 1968: Any assumption of rights of owner\n\nKey points:\n- Can be with owner's consent (Gomez)\n- Can be of gift (Hinks)\n- Includes single right of owner\n- Can be continuing act\n- Later assumption also counts",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["appropriation", "assumption", "gomez", "hinks"],
    },
    {
      id: "crl-017",
      front: "What is dishonesty in theft?",
      back: "s.2 Theft Act 1968 - Not dishonest if:\n1. Believes has right in law\n2. Believes owner would consent\n3. Believes owner cannot be found\n\nOtherwise: Ivey test - objective standard of ordinary decent people",
      category: "criminal-law-principles",
      difficulty: "intermediate",
      tags: ["dishonesty", "section-2", "ivey", "objective"],
    },
    {
      id: "crl-018",
      front: "What is robbery?",
      back: "s.8 Theft Act 1968: Theft with force or threat of force\n\nElements:\n1. Theft (all elements must be present)\n2. Force or threat of force\n3. Immediately before or at time of theft\n4. In order to steal\n\nForce can be minimal",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["robbery", "theft", "force", "threat"],
    },
    {
      id: "crl-019",
      front: "What is burglary?",
      back: "s.9 Theft Act 1968:\n\ns.9(1)(a): Enters building as trespasser with intent to steal/inflict GBH/damage\n\ns.9(1)(b): Having entered as trespasser, steals/attempts to steal or inflicts/attempts GBH\n\nEntry can be partial. Building includes inhabited vehicles/vessels",
      category: "criminal-law-principles",
      difficulty: "foundation",
      tags: ["burglary", "trespasser", "building", "entry"],
    },
    {
      id: "crl-020",
      front: "What are the inchoate offences?",
      back: "1. Attempt - Trying to commit offence (more than merely preparatory)\n2. Conspiracy - Agreement to commit offence\n3. Incitement/Encouraging - Encouraging another to commit offence\n\nAll require intent to commit full offence.\nImpossibility generally no defence to attempt",
      category: "criminal-law-principles",
      difficulty: "advanced",
      tags: ["inchoate", "attempt", "conspiracy", "encouraging"],
    },
  ],

  "analysis-of-claims": [
    {
      id: "ac-001",
      front: "What is the Civil Procedure Rules overriding objective?",
      back: "CPR 1.1 - To enable courts to deal with cases justly and at proportionate cost.\n\nIncludes:\n- Ensuring parties on equal footing\n- Saving expense\n- Dealing with cases proportionately\n- Ensuring expedition\n- Allotting appropriate share of court resources\n- Enforcing compliance with rules",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["cpr", "overriding-objective", "proportionality"],
    },
    {
      id: "ac-002",
      front: "What are the different tracks in civil litigation?",
      back: "Small Claims Track:\n- Claims up to £10,000\n- Informal procedure\n- Limited costs recovery\n\nFast Track:\n- Claims £10,000-£25,000\n- Standard directions\n- Trial limited to 1 day\n\nMulti-Track:\n- Claims over £25,000\n- Case management conferences\n- No trial time limit",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["tracks", "case-management", "small-claims"],
    },
    {
      id: "ac-003",
      front: "What is the standard of proof in civil cases?",
      back: "Balance of probabilities - More likely than not (>50%)\n\nContrast with criminal standard: Beyond reasonable doubt\n\nFor serious allegations in civil cases, cogent evidence required but standard remains balance of probabilities (Re H and others).",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["standard-of-proof", "balance-of-probabilities", "evidence"],
    },
    {
      id: "ac-004",
      front: "What are the rules for summary judgment?",
      back: "CPR Part 24 - Court may give summary judgment if:\n1. Claimant has no real prospect of succeeding on claim/issue, OR\n2. Defendant has no real prospect of successfully defending claim/issue\n3. AND there is no other compelling reason for trial\n\nApplication can be made after acknowledgment of service filed.",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["summary-judgment", "real-prospect", "cpr-24"],
    },
    {
      id: "ac-005",
      front: "What is the general rule for costs in civil litigation?",
      back: "CPR 44.2 - The unsuccessful party pays the successful party's costs.\n\nCourt considers:\n- Conduct of parties\n- Whether party succeeded on part of case\n- Admissible offers to settle\n- Whether it was reasonable to raise/contest issues\n- Manner in which party pursued case",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["costs", "unsuccessful-party", "conduct"],
    },
    {
      id: "ac-006",
      front: "What are the pre-action protocols?",
      back: "Procedures parties should follow before starting proceedings:\n- Exchange information\n- Investigate claims\n- Consider ADR\n- Comply with specific protocol requirements\n\nSanctions for non-compliance:\n- Costs penalties\n- Interest penalties\n- Case management directions",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["pre-action-protocols", "adr", "sanctions"],
    },
    {
      id: "ac-007",
      front: "What are the different types of claim forms?",
      back: "N1 - General claim form\nN208 - Part 8 claim form (no substantial dispute of fact)\nN5A - Possession claim\nN5B - Possession claim (accelerated procedure)\nN244 - Application notice\nPF1 - Probate claim form",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["claim-forms", "n1", "part-8"],
    },
    {
      id: "ac-008",
      front: "What are the time limits for responding to claims?",
      back: "Acknowledgment of Service: 14 days from service\nDefence: 14 days from service (or 28 days if acknowledgment filed)\nCounterclaim: Same time as defence\nReply: 14 days from service of defence\n\nExtensions possible by agreement or court order",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["time-limits", "acknowledgment", "defence"],
    },
    {
      id: "ac-009",
      front: "What are the different methods of service?",
      back: "Personal service - Handing document to person\nFirst class post - To usual/last known address\nLeaving at address - With responsible person\nFax - If number provided for service\nEmail - If agreed or court orders\nDX - If number provided\nThrough solicitor - If acting",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["service", "personal-service", "post"],
    },
    {
      id: "ac-010",
      front: "What is a Part 36 offer?",
      back: "Formal settlement offer with costs consequences:\n- Must be open for 21 days\n- Can be made by either party\n- If not beaten at trial, costs consequences follow\n- Claimant: defendant pays costs from expiry + enhanced damages\n- Defendant: claimant pays costs from expiry",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["part-36", "settlement", "costs-consequences"],
    },
    {
      id: "ac-011",
      front: "What are the different types of interim applications?",
      back: "Summary judgment - No real prospect of success\nStrike out - No reasonable grounds/abuse of process\nInterim injunction - Preserve status quo\nFreezing order - Prevent asset dissipation\nSearch order - Preserve evidence\nSecurity for costs - Ensure costs can be paid",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["interim-applications", "injunction", "freezing-order"],
    },
    {
      id: "ac-012",
      front: "What is the test for interim injunctions?",
      back: "American Cyanamid test:\n1. Serious question to be tried\n2. Damages adequate remedy?\n3. Balance of convenience\n4. Status quo\n5. Special factors\n\nMandatory injunctions: higher threshold - high degree of assurance of success",
      category: "analysis-of-claims",
      difficulty: "advanced",
      tags: ["interim-injunction", "american-cyanamid", "balance-of-convenience"],
    },
    {
      id: "ac-013",
      front: "What are the requirements for a freezing order?",
      back: "Requirements:\n1. Good arguable case\n2. Real risk of dissipation\n3. Just and convenient to grant\n4. Undertaking in damages\n\nWorldwide freezing orders possible but higher threshold.\nMust give full and frank disclosure",
      category: "analysis-of-claims",
      difficulty: "advanced",
      tags: ["freezing-order", "dissipation", "undertaking-damages"],
    },
    {
      id: "ac-014",
      front: "What is disclosure in civil proceedings?",
      back: "Standard disclosure (CPR 31.6):\n- Documents on which party relies\n- Documents which adversely affect party's case\n- Documents which adversely affect another party's case\n- Documents which support another party's case\n\nDuty continues throughout proceedings",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["disclosure", "standard-disclosure", "cpr-31"],
    },
    {
      id: "ac-015",
      front: "What are the different types of evidence?",
      back: "Witness statements - Written evidence of witnesses\nExpert evidence - Opinion evidence from experts\nReal evidence - Physical objects\nDocumentary evidence - Documents and records\nHearsay evidence - Second-hand evidence (notice required)\nAdmissions - Formal admissions of fact",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["evidence", "witness-statements", "expert-evidence"],
    },
    {
      id: "ac-016",
      front: "What are the rules for expert evidence?",
      back: "CPR Part 35:\n- Expert's duty to court overrides duty to party\n- Single joint expert preferred\n- Permission required for expert evidence\n- Experts must meet and identify issues\n- Expert can be called to give oral evidence",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["expert-evidence", "cpr-35", "single-joint-expert"],
    },
    {
      id: "ac-017",
      front: "What is case management in civil proceedings?",
      back: "Court's active management of cases:\n- Allocation to appropriate track\n- Setting timetables\n- Limiting issues and evidence\n- Encouraging settlement\n- Controlling costs\n- Making use of technology\n\nCase management conferences and pre-trial reviews",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["case-management", "allocation", "timetables"],
    },
    {
      id: "ac-018",
      front: "What are the different types of judgment?",
      back: "Default judgment - Failure to respond\nSummary judgment - No real prospect of success\nJudgment after trial - Following full trial\nConsent judgment - Agreed by parties\nTomlin order - Settlement with liberty to apply\nJudgment in default of defence - No defence filed",
      category: "analysis-of-claims",
      difficulty: "foundation",
      tags: ["judgment", "default", "consent", "tomlin"],
    },
    {
      id: "ac-019",
      front: "What are the methods of enforcement?",
      back: "Money judgments:\n- Warrant of control (goods)\n- Attachment of earnings\n- Third party debt order\n- Charging order\n- Bankruptcy/winding up\n\nNon-money judgments:\n- Committal for contempt\n- Writ of sequestration",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["enforcement", "warrant-of-control", "charging-order"],
    },
    {
      id: "ac-020",
      front: "What are the grounds for appeal?",
      back: "Permission required except in limited circumstances.\n\nGrounds:\n- Wrong in law\n- Wrong in fact\n- Procedurally unfair\n- Decision outside reasonable range\n\nReal prospect of success OR compelling reason for appeal",
      category: "analysis-of-claims",
      difficulty: "intermediate",
      tags: ["appeal", "permission", "real-prospect"],
    },
  ],
}

export const getFlashcardsByCategory = (category: string): Flashcard[] => {
  return flashcardsDatabase[category] || []
}

export const getAllCategories = (): string[] => {
  return Object.keys(flashcardsDatabase)
}

export const getFlashcardById = (id: string): Flashcard | undefined => {
  for (const category of Object.values(flashcardsDatabase)) {
    const flashcard = category.find((f) => f.id === id)
    if (flashcard) return flashcard
  }
  return undefined
}

export const getFlashcardsByDifficulty = (difficulty: "foundation" | "intermediate" | "advanced"): Flashcard[] => {
  const allFlashcards: Flashcard[] = []
  for (const category of Object.values(flashcardsDatabase)) {
    allFlashcards.push(...category.filter((f) => f.difficulty === difficulty))
  }
  return allFlashcards
}

export const getFlashcardsByTag = (tag: string): Flashcard[] => {
  const allFlashcards: Flashcard[] = []
  for (const category of Object.values(flashcardsDatabase)) {
    allFlashcards.push(...category.filter((f) => f.tags.includes(tag)))
  }
  return allFlashcards
}

export const getRandomFlashcards = (count: number, category?: string): Flashcard[] => {
  let flashcards: Flashcard[] = []

  if (category) {
    flashcards = getFlashcardsByCategory(category)
  } else {
    for (const categoryFlashcards of Object.values(flashcardsDatabase)) {
      flashcards.push(...categoryFlashcards)
    }
  }

  // Shuffle and return requested count
  const shuffled = flashcards.sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

export const getTotalFlashcardCount = (): number => {
  let total = 0
  for (const category of Object.values(flashcardsDatabase)) {
    total += category.length
  }
  return total
}

export const getCategoryStats = () => {
  const stats: Record<string, { total: number; foundation: number; intermediate: number; advanced: number }> = {}

  for (const [categoryName, flashcards] of Object.entries(flashcardsDatabase)) {
    stats[categoryName] = {
      total: flashcards.length,
      foundation: flashcards.filter((f) => f.difficulty === "foundation").length,
      intermediate: flashcards.filter((f) => f.difficulty === "intermediate").length,
      advanced: flashcards.filter((f) => f.difficulty === "advanced").length,
    }
  }

  return stats
}
